name: Build Windows App (Folder Version)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build (non-onefile) EXE with PyInstaller
        run: |
          pyinstaller --noconfirm --windowed ^
            --add-data "questions.db;." ^
            --add-data "qt.conf;." ^
            --add-data "icon.ico;." ^
            main.py

      - name: Upload folder as zip
        uses: actions/upload-artifact@v4
        with:
          name: personal-assistant-folder
          path: dist/main
