name: Build Windows App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Upgrade pip
        run: python -m ensurepip --upgrade

      - name: Create pyproject.toml
        run: |
          echo "[build-system]
          requires = ['briefcase']
          build-backend = 'briefcase.bootstrap'

          [tool.briefcase]
          project_name = 'myapp'
          bundle = 'com.example'
          version = '0.1.0'
          url = 'https://example.com'
          license = 'BSD'
          author = 'Jane Developer'
          author_email = 'jane@example.com'

          [tool.briefcase.app.myapp]
          formal_name = 'My App'
          description = 'My first Briefcase app'
          sources = ['src/myapp']
          requires = []" > pyproject.toml

      - name: Create Basic App Structure
        run: |
          mkdir -p src/myapp
          echo "def main():
              print('Hello, World!')
          
          if __name__ == '__main__':
              main()" > src/myapp/__main__.py
          echo "__version__ = '0.1.0'" > src/myapp/__init__.py

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install briefcase

      - name: Build Windows App
        run: |
          briefcase create windows
          briefcase build windows
          briefcase package windows

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/
