name: Build Windows Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      # التحقق من إعدادات العمل
      - name: Checkout code
        uses: actions/checkout@v4

      # ضبط إصدار Python الصحيح
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      # التحقق من وجود pip
      - name: Verify pip installation
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip

      # التحقق من وجود pyproject.toml
      - name: Verify pyproject.toml
        shell: pwsh
        run: |
          if (!(Test-Path "pyproject.toml")) {
            Write-Error "pyproject.toml not found!";
            exit 1;
          }

      # تثبيت المتطلبات
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      # تثبيت Briefcase
      - name: Install Briefcase
        run: |
          pip install briefcase

      # بناء التطبيق لنظام Windows
      - name: Build Windows App
        run: |
          briefcase create windows
          briefcase build windows
          briefcase package windows

      # رفع النتائج (اختياري)
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/
