name: All Builds (Linux, macOS, Windows, Android, APK)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.12
  FLUTTER_VERSION: 3.22.2
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        pip install pyobjc

    - name: Clean Build Directory
      run: |
        rm -rf build dist

    - name: Build macOS App
      run: |
        python setup.py py2app

    - name: Upload macOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: dist/

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt

    - name: Build Windows App
      run: |
        pyinstaller --onefile main.py

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: dist/
