name: Build Windows Application

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9  # إصدار مضمون مع pip

      - name: Verify pip installation
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip

      - name: Install Dependencies
        run: python -m pip install -r requirements.txt

      - name: Install Briefcase
        run: python -m pip install briefcase

      - name: Build Windows App
        shell: powershell
        run: |
          if (!(Test-Path "pyproject.toml")) {
            Write-Error "Error: pyproject.toml not found"
            exit 1
          }
          briefcase create windows
          briefcase build windows
          briefcase package windows

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/
