name: Build Windows Application

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Dependencies
        run: python -m pip install -r requirements.txt

      - name: Install Briefcase
        run: python -m pip install briefcase

      - name: Build Windows App
        run: |
          if [ ! -f "pyproject.toml" ]; then
            echo "Error: pyproject.toml not found"
            exit 1
          fi
          briefcase create windows
          briefcase build windows
          briefcase package windows

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/
