name: Build Windows App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Create Source Directory
        run: |
          mkdir -p src/assistant_app
          if (!(Test-Path src/assistant_app/__main__.py)) {
            echo "def main():
                print('Hello, World!')
            
            if __name__ == '__main__':
                main()" > src/assistant_app/__main__.py
          }
          if (!(Test-Path src/assistant_app/__init__.py)) {
            echo "__version__ = '1.0.0'" > src/assistant_app/__init__.py
          }

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install briefcase
          # تثبيت المتطلبات الإضافية إذا كانت موجودة في requirements.txt
          if (Test-Path requirements.txt) {
            pip install -r requirements.txt
          }

      - name: Build Windows App
        run: |
          briefcase create windows
          briefcase build windows
          briefcase package windows

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: assistant-app-windows
          path: |
            windows/*/assistant_app*.msi
            windows/*/assistant_app*.exe
