name: Build Windows EXE (Final Version)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          pip install Pillow   # ✅ هذا هو السطر المطلوب لتفادي خطأ الأيقونة

      - name: Build EXE with PyInstaller (with icon)
        run: |
          pyinstaller --noconfirm --windowed --name raeef_assistant --icon=icon.ico main.py

      - name: Copy required files to output folder
        run: |
          copy questions.db dist\raeef_assistant\

      - name: Upload final app folder
        uses: actions/upload-artifact@v4
        with:
          name: raeef-assistant-final
          path: dist/raeef_assistant
