name: Build Windows Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Python 3.9
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      # Upgrade pip
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      # Verify pyproject.toml
      - name: Verify pyproject.toml
        run: |
          if not exist pyproject.toml (
            echo "pyproject.toml not found!" && exit 1
          )

      # Install dependencies
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      # Install Briefcase
      - name: Install Briefcase
        run: |
          pip install briefcase

      # Build Windows Application
      - name: Build Windows App
        run: |
          briefcase create windows
          briefcase build windows
          briefcase package windows

      # Upload Windows Artifact
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/
