name: Build Windows App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Update pyproject.toml
        run: |
          @'
          [build-system]
          requires = ["briefcase"]
          build-backend = "briefcase.bootstrap"

          [tool.briefcase]
          project_name = "assistant_app"
          version = "1.0.0"
          bundle = "com.myline70.assistantapp"
          description = "Assistant Application"
          author = "Author Name"
          author_email = "author@example.com"
          license = "MIT"
          url = "https://github.com/myline70/Raeef"

          [tool.briefcase.app.assistant_app]
          formal_name = "Assistant Application"
          description = "Assistant Application"
          icon = "src/assistant_app/resources/assistant_app"
          sources = ["src/assistant_app"]
          requires = [
              "briefcase",
          ]
          license = "MIT"
          '@ | Out-File -FilePath pyproject.toml -Encoding UTF8

      - name: Create Source Directory
        run: |
          mkdir -p src/assistant_app
          mkdir -p src/assistant_app/resources
          @'
          def main():
              print("Hello, World!")

          if __name__ == '__main__':
              main()
          '@ | Out-File -FilePath src/assistant_app/__main__.py -Encoding UTF8
          
          @'
          __version__ = "1.0.0"
          '@ | Out-File -FilePath src/assistant_app/__init__.py -Encoding UTF8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install briefcase

      - name: Build Windows App
        run: |
          briefcase create windows
          briefcase build windows
          briefcase package windows

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: assistant-app-windows
          path: |
            windows/*/assistant_app*.msi
            windows/*/assistant_app*.exe
