name: Build Windows App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      # 3. Upgrade pip and install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install briefcase

      # 4. Build the application
      - name: Build Windows App
        run: |
          briefcase create windows
          briefcase build windows
          briefcase package windows

      # 5. List Build Directory (Debugging)
      - name: List Build Directory
        run: |
          dir dist

      # 6. Upload Windows Artifact
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: assistant-app-windows
          path: |
            dist\*.msi
            dist\*.exe
