name: Build Windows App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      # 3. Create or Update pyproject.toml
      - name: Create or Update pyproject.toml
        run: |
          @"
          [build-system]
          requires = ["briefcase"]
          build-backend = "briefcase.bootstrap"

          [tool.briefcase]
          project_name = "assistant_app"
          version = "1.0.0"
          bundle = "com.myline70.assistantapp"
          description = "Assistant Application"
          author = "Author Name"
          author_email = "author@example.com"
          license = "MIT"
          url = "https://github.com/myline70/Raeef"

          [tool.briefcase.app.assistant_app]
          formal_name = "Assistant Application"
          description = "Assistant Application"
          sources = ["src/assistant_app"]
          requires = [
              "briefcase",
          ]
          "@ | Out-File -FilePath pyproject.toml -Encoding UTF8

      # 4. Verify pyproject.toml
      - name: Verify pyproject.toml
        run: |
          if (-Not (Test-Path -Path "pyproject.toml")) {
              Write-Host "pyproject.toml not found!";
              exit 1;
          }
          if (-Not (Select-String -Path "pyproject.toml" -Pattern 'project_name = "assistant_app"')) {
              Write-Host "project_name is missing in pyproject.toml!";
              exit 1;
          }

      # 5. Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install briefcase

      # 6. Build the application
      - name: Build Windows App
        run: |
          briefcase create windows
          briefcase build windows
          briefcase package windows

      # 7. List Build Directory (Debugging)
      - name: List Build Directory
        run: |
          Get-ChildItem -Path dist

      # 8. Upload Windows Artifact
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: assistant-app-windows
          path: |
            dist\*.msi
            dist\*.exe
