name: Build macOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build app with PyInstaller
        run: |
          pyinstaller --noconfirm --windowed \
            --name raeef_assistant \
            --icon=icon.icns \
            --add-data "qt.conf:." \
            main.py

      - name: Compress .app to ZIP
        run: |
          cd dist
          ditto -c -k --sequesterRsrc --keepParent raeef_assistant.app raeef-assistant-mac.zip

      - name: Upload app ZIP
        uses: actions/upload-artifact@v4
        with:
          name: raeef-assistant-mac
          path: dist/raeef-assistant-mac.zip
